eureka:
  client:
    serviceUrl:
      defaultZone: http://lidongyang:123456@localhost:8888/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: eureka-consumer
  boot:
    admin:
      client:
        url:
        instance:
          service-url: localhost:8082


server:
  port: 8083
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


