eureka:
  client:
    serviceUrl:
      defaultZone: http://lidongyang:123456@localhost:8888/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: eureka-consumer


server:
  port: 8083
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

